version: "3.9"
services:
  web:
    image: singers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - DOCDB_ENDPOINT=mongo
      - DOCDB_PORT=27017
      - DOCDB_USERNAME=admin
      - DOCDB_PASSWORD=password1
  mongo:
    container_name: mongo 
    image: mongo:5.0.15-focal 
    ports:
      - 27017:27017
    volumes:
      - ~/data/karoke-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password1